import type { ReferenceCandidate } from "./schema/types";

/** 演示允许的参考库。必须标识“演示参考值”，不得伪装成当前项目事实。 */
export const DEMO_REFERENCES: ReferenceCandidate[] = [
  {
    field_code: "ops.trips_per_vehicle_month",
    suggested_value: "9",
    range_min: "7",
    range_max: "12",
    source_level: "demo_history",
    sample_size: 8,
    statistic_method: "median",
    source_updated_at: "2026-09-01T00:00:00.000Z",
    applicable_condition: "演示参考值 / 同线路历史样本中位数，不是本合同台账。",
    confidence_level: "demo",
    status: "unused",
  },
  {
    field_code: "cargo.load_ton",
    suggested_value: "33",
    range_min: "28",
    range_max: "35",
    source_level: "demo_vehicle",
    sample_size: 12,
    statistic_method: "median",
    source_updated_at: "2026-09-01T00:00:00.000Z",
    applicable_condition: "演示参考值 / 同车型载重样本，需现场核实。",
    confidence_level: "demo",
    status: "unused",
  },
  {
    field_code: "vehicle.monthly_rent",
    suggested_value: "6500",
    range_min: "5200",
    range_max: "7800",
    source_level: "demo_history",
    sample_size: 6,
    statistic_method: "median",
    source_updated_at: "2026-09-01T00:00:00.000Z",
    applicable_condition: "演示参考值 / 融资租赁样本月租，禁止当作已签合同。",
    confidence_level: "demo",
    status: "unused",
  },
  {
    field_code: "energy.loaded_consumption",
    suggested_value: "1.35",
    range_min: "1.2",
    range_max: "1.5",
    source_level: "demo_vehicle",
    sample_size: 10,
    statistic_method: "median",
    source_updated_at: "2026-09-01T00:00:00.000Z",
    applicable_condition: "演示参考值 / 同车型满载电耗中位数，不是实测。",
    confidence_level: "demo",
    status: "unused",
  },
  {
    field_code: "energy.empty_consumption",
    suggested_value: "0.95",
    range_min: "0.8",
    range_max: "1.1",
    source_level: "demo_vehicle",
    sample_size: 10,
    statistic_method: "median",
    source_updated_at: "2026-09-01T00:00:00.000Z",
    applicable_condition: "演示参考值 / 同车型空载电耗中位数，不是实测。",
    confidence_level: "demo",
    status: "unused",
  },
  {
    field_code: "energy.electricity_price",
    suggested_value: "0.82",
    range_min: "0.6",
    range_max: "1.0",
    source_level: "demo_history",
    sample_size: 6,
    statistic_method: "median",
    source_updated_at: "2026-09-01T00:00:00.000Z",
    applicable_condition: "演示参考值 / 场站电价样本，禁止当作已锁定合同电价。",
    confidence_level: "demo",
    status: "unused",
  },
];
